const AI_TOOLS=[
 {name:"get_safe_to_spend",description:"Balance minus unpaid DDs due BEFORE payday. Post-payday DDs excluded (salary covers them).",input_schema:{type:"object",properties:{}}},
 {name:"get_balances",description:"Balance per bank and total.",input_schema:{type:"object",properties:{}}},
 {name:"get_income_and_payday",description:"Monthly net income and next payday.",input_schema:{type:"object",properties:{}}},
 {name:"get_direct_debits",description:"All DDs with bank, paid, period this/next.",input_schema:{type:"object",properties:{}}},
 {name:"get_debts",description:"Loans and credit cards.",input_schema:{type:"object",properties:{}}},
 {name:"get_savable_this_period",description:"Savable before payday with pro-rated variable reality-check.",input_schema:{type:"object",properties:{}}},
 {name:"get_spending_by_category",description:"Spend per category over N months.",input_schema:{type:"object",properties:{months:{type:"number"}}}},
 {name:"search_transactions",description:"Search transactions by keyword.",input_schema:{type:"object",properties:{query:{type:"string"},months:{type:"number"}},required:["query"]}},
 {name:"get_goals",description:"Savings goals.",input_schema:{type:"object",properties:{}}}
];
function _prePaydayDDs(dds){return dds.filter(d=>d.dueThisMonth&&!d.paid&&!d._paused&&!d.isPostPayday);}
function _postPaydayDDs(dds){return dds.filter(d=>d.dueThisMonth&&!d._paused&&d.isPostPayday);}
async function runAITool(name,input){input=input||{};try{
 if(name==="get_safe_to_spend"){const b=await getAllBalances();const total=Object.values(b).reduce((a,v)=>a+(parseFloat(v)||0),0);const dds=window._classifiedDDs||[];const pre=_prePaydayDDs(dds);const post=_postPaydayDDs(dds);const pt=pre.reduce((a,d)=>a+d.amount,0);return{safeToSpend:+(total-pt).toFixed(2),totalBalance:+total.toFixed(2),unpaidDDsBeforePayday:+pt.toFixed(2),beforePaydayItems:pre.map(d=>({name:d.name,amount:d.amount,day:d.dayOfMonth,bank:d.bank||"unassigned"})),coveredByNextSalary:post.map(d=>({name:d.name,amount:d.amount,day:d.dayOfMonth})),note:"Balance minus unpaid pre-payday DDs. Post-payday DDs covered by incoming salary, excluded."};}
 if(name==="get_balances"){const b=await getAllBalances();const L={ptsb:"PTSB",boi:"Bank of Ireland",revolut:"Revolut"};return{balances:Object.entries(b).map(([k,v])=>({bank:L[k]||k,balance:+(parseFloat(v)||0).toFixed(2)})),total:+Object.values(b).reduce((a,v)=>a+(parseFloat(v)||0),0).toFixed(2)};}
 if(name==="get_income_and_payday"){const n=new Date();const p=await expectedPayday(n.getFullYear(),n.getMonth());const period=window._currentDDPeriod||{};return{monthlyNetIncome:getMonthlyIncome()||0,nextPaydayDay:p,currentPeriodEnd:period.end||null};}
 if(name==="get_direct_debits"){const dds=window._classifiedDDs||[];const L={ptsb:"PTSB",boi:"BoI",revolut:"Revolut"};return{directDebits:dds.map(d=>({name:d.name,amount:d.amount,dayOfMonth:d.dayOfMonth,bank:d.bank?(L[d.bank]||d.bank):"unassigned",paid:!!d.paid,period:d.isPostPayday?"next (salary-covered)":"this",paused:!!d._paused,frequency:d.frequency===0?"weekly":(d.frequency||1)+"-monthly"}))};}
 if(name==="get_debts"){const dt=await dbGetAll("debts");return{debts:dt.map(d=>({name:d.name,type:d.type,balance:d.balance,apr:d.rate,monthlyPayment:d.monthlyPayment||0,limit:d.limit||null,dueDay:d.dueDayOfMonth||null}))};}
 if(name==="get_savable_this_period"){const b=await getAllBalances();const total=Object.values(b).reduce((a,v)=>a+(parseFloat(v)||0),0);const dds=window._classifiedDDs||[];const pre=_prePaydayDDs(dds);const post=_postPaydayDDs(dds);const ddBefore=pre.reduce((a,d)=>a+d.amount,0);const savableBeforeVariable=total-ddBefore;const period=window._currentDDPeriod||{};let days=null;if(period.end){const end=new Date(period.end);const now=new Date();days=Math.max(0,Math.ceil((end-now)/86400000));}const monthlyVar=(getBudgetCats()||[]).reduce((a,x)=>a+(x.amount||0),0);const estVar=days!=null?+((monthlyVar/30)*days).toFixed(2):null;const realistic=estVar!=null?+(savableBeforeVariable-estVar).toFixed(2):null;return{savableBeforeVariable:+savableBeforeVariable.toFixed(2),totalBalance:+total.toFixed(2),ddsBeforePayday:+ddBefore.toFixed(2),daysUntilPayday:days,monthlyVariableBudget:+monthlyVar.toFixed(2),estimatedVariableBeforePayday:estVar,realisticSavableAfterEstimatedVariable:realistic,coveredByNextSalary:post.map(d=>({name:d.name,amount:d.amount,day:d.dayOfMonth})),note:"HEADLINE savableBeforeVariable. Then reality-check: ~estimatedVariableBeforePayday over daysUntilPayday days, realistically ~realisticSavableAfterEstimatedVariable. Post-payday DDs NOT subtracted."};}
 if(name==="get_spending_by_category"){const m=input.months||3;const tx=await dbGetAll("transactions");const co=new Date();co.setMonth(co.getMonth()-m);const cs=co.toISOString().slice(0,10);const bc={};tx.filter(t=>!t.isCredit&&!t.isInternal&&t.date>=cs).forEach(t=>{bc[t.category||"Unknown"]=(bc[t.category||"Unknown"]||0)+t.amount;});return{months:m,byCategory:Object.entries(bc).sort((a,b)=>b[1]-a[1]).map(([ct,t])=>({category:ct,total:+t.toFixed(2),perMonth:+(t/m).toFixed(2)}))};}
 if(name==="search_transactions"){const q=(input.query||"").toLowerCase();const m=input.months||6;const tx=await dbGetAll("transactions");const co=new Date();co.setMonth(co.getMonth()-m);const cs=co.toISOString().slice(0,10);const mt=tx.filter(t=>!t.isInternal&&t.date>=cs&&((t.description||"").toLowerCase().includes(q)||(t.category||"").toLowerCase().includes(q)));const tot=mt.reduce((a,t)=>a+t.amount,0);return{query:input.query,monthsSearched:m,count:mt.length,totalSpent:+tot.toFixed(2),average:mt.length?+(tot/mt.length).toFixed(2):0,transactions:mt.slice(0,25).map(t=>({date:t.date,description:t.description,amount:t.amount,category:t.category}))};}
 if(name==="get_goals"){let g=[];try{g=await dbGetAll("goals");}catch(e){}return{goals:g.map(x=>({name:x.name,type:x.type,target:x.targetAmount,targetDate:x.targetDate||null,saved:x.savedSoFar||0,monthlyContribution:x.monthlyContribution||0}))};}
 return{error:"Unknown tool: "+name};}catch(err){return{error:err.message};}}
function buildToolSystemPrompt(){const now=new Date();return "You are VaultLocal AI, a private financial assistant. Data is local. Use euro. Be concise. Today is "+now.toLocaleDateString("en-IE",{weekday:"long",day:"numeric",month:"long",year:"numeric"})+". ALWAYS call the relevant tool before answering. NEVER guess numbers. LOGIC: 1) get_safe_to_spend = balance minus unpaid DDs BEFORE payday; post-payday DDs (coveredByNextSalary) NOT counted, salary covers them, mention only as heads-up. 2) How much can I save -> get_savable_this_period: HEADLINE savableBeforeVariable, THEN reality-check that based on the variable budget youd typically spend about estimatedVariableBeforePayday euro over daysUntilPayday days so realistically about realisticSavableAfterEstimatedVariable euro; never count post-payday DDs against savings. 3) Afford X based on history -> search_transactions, try category terms like eating out or restaurant if exact word finds nothing. 4) Which bank -> get_direct_debits. 5) This period or next -> period field, next means salary-covered. 6) Surplus priority: goals/pre-orders soonest, then planned purchases, then overpay highest-APR loan.";}
async function callBedrockChatWithTools(history){const url=(localStorage.getItem("bedrock_proxy_url")||"").trim();const key=(localStorage.getItem("bedrock_api_key")||"").trim();if(!url)return"Bedrock proxy URL not configured.";let messages=history.map(m=>({role:m.role==="assistant"?"assistant":"user",content:m.content}));const system=buildToolSystemPrompt();for(let turn=0;turn<6;turn++){const res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json",...(key?{"x-api-key":key}:{})},body:JSON.stringify({messages,system,tools:AI_TOOLS,max_tokens:4096})});if(!res.ok){const t=await res.text();return"AI error: "+res.status+" "+t;}const data=await res.json();const content=data.content||[];const toolUses=content.filter(c=>c.type==="tool_use");if(toolUses.length===0){return content.filter(c=>c.type==="text").map(c=>c.text).join("\n")||"(no response)";}messages.push({role:"assistant",content});const toolResults=[];for(const tu of toolUses){console.log("[AI tool]",tu.name,tu.input);const out=await runAITool(tu.name,tu.input);console.log("[AI result]",tu.name,out);toolResults.push({type:"tool_result",tool_use_id:tu.id,content:JSON.stringify(out)});}messages.push({role:"user",content:toolResults});}return"AI stopped after too many tool calls.";}
async function getGoals(){try{return await dbGetAll("goals");}catch(e){return[];}}
async function saveGoal(g){return await dbPut("goals",g);}
console.log("[ai-tools] loaded:",typeof callBedrockChatWithTools);
