const AI_TOOLS=[
 {name:"get_safe_to_spend",description:"Balance minus unpaid DDs due BEFORE payday. Post-payday DDs excluded (salary covers them).",input_schema:{type:"object",properties:{}}},
 {name:"get_balances",description:"Balance per bank and total.",input_schema:{type:"object",properties:{}}},
 {name:"get_income_and_payday",description:"Monthly net income and next payday.",input_schema:{type:"object",properties:{}}},
 {name:"get_direct_debits",description:"All DDs with bank, paid, period this/next.",input_schema:{type:"object",properties:{}}},
 {name:"get_pending_this_period",description:"Unpaid DDs in the current period split into counted (before payday), paused (not counted), and next-period (salary-covered). Use for any 'pending' or 'DDs left this month' question. Quote pendingBeforePaydayTotal verbatim.",input_schema:{type:"object",properties:{}}},
 {name:"get_debts",description:"Loans and credit cards.",input_schema:{type:"object",properties:{}}},
 {name:"get_savable_this_period",description:"Savable before payday with pro-rated variable reality-check.",input_schema:{type:"object",properties:{}}},
 {name:"get_spending_by_category",description:"Spend per category over N months.",input_schema:{type:"object",properties:{months:{type:"number"}}}},
 {name:"search_transactions",description:"Search transactions by keyword and/or time window. Optional: period ('current'|'last'|'last3', uses salary dates from settings for exact payday-to-payday boundaries), startDate/endDate ('YYYY-MM-DD' explicit range), bank ('ptsb'|'boi'|'revolut'). Filters on transaction date only. Returns the resolved periodStart/periodEnd so you can state the exact window searched.",input_schema:{type:"object",properties:{query:{type:"string"},months:{type:"number"},period:{type:"string"},startDate:{type:"string"},endDate:{type:"string"},bank:{type:"string"}}}},
 {name:"find_recurring_charges",description:"Detects recurring charges over the last 3 pay periods by fuzzy-grouping merchant names (strips POS/DD prefixes, dates, case). Flags items appearing in >=2 of 3 periods with similar amount (+-20%) and day (+-5d). Cross-checks against the DD schedule. Use for 'recurring charges not in my DD schedule', 'typical DDs', or 'what bills repeat'. The key output is notInSchedule: recurring charges NOT yet tracked as DDs.",input_schema:{type:"object",properties:{}}},
 {name:"get_goals",description:"Savings goals.",input_schema:{type:"object",properties:{}}}
];
function _prePaydayDDs(dds){return dds.filter(d=>d.dueThisMonth&&!d.paid&&!d._paused&&!d.isPostPayday);}
function _salaryDates(){try{return (getSalaryDates&&getSalaryDates())||[];}catch(e){return[];}}
function _periodWindow(which){const sd=_salaryDates().slice().sort();const today=new Date().toISOString().slice(0,10);let idx=-1;for(let i=0;i<sd.length;i++){if(sd[i]<=today)idx=i;}/*idx=last payday on/before today=start of current period*/if(idx<0)return null;if(which==="current"){return{start:sd[idx],end:sd[idx+1]||null};}if(which==="last"){return{start:sd[idx-1]||null,end:sd[idx]};}if(which==="last3"){return{start:sd[Math.max(0,idx-3)]||null,end:sd[idx]};}return null;}
function _normMerchant(s){return (s||"").toLowerCase().replace(/\bpos\b|\bdd\b|\bso\b|\bvisa\b|\bsepa\b/g,"").replace(/\d{1,2}[\/-]\d{1,2}([\/-]\d{2,4})?/g,"").replace(/\d{2,}/g,"").replace(/[^a-z ]/g," ").replace(/\s+/g," ").trim().slice(0,18);}
function _postPaydayDDs(dds){return dds.filter(d=>d.dueThisMonth&&!d._paused&&d.isPostPayday);}
function _pausedDDs(dds){return dds.filter(d=>d.dueThisMonth&&!d.paid&&d._paused);}
async function runAITool(name,input){input=input||{};try{
 if(name==="get_safe_to_spend"){const b=await getAllBalances();const total=Object.values(b).reduce((a,v)=>a+(parseFloat(v)||0),0);const dds=window._classifiedDDs||[];const pre=_prePaydayDDs(dds);const post=_postPaydayDDs(dds);const pt=pre.reduce((a,d)=>a+d.amount,0);return{safeToSpend:+(total-pt).toFixed(2),totalBalance:+total.toFixed(2),unpaidDDsBeforePayday:+pt.toFixed(2),beforePaydayItems:pre.map(d=>({name:d.name,amount:d.amount,day:d.dayOfMonth,bank:d.bank||"unassigned"})),coveredByNextSalary:post.map(d=>({name:d.name,amount:d.amount,day:d.dayOfMonth})),note:"Balance minus unpaid pre-payday DDs. Post-payday DDs covered by incoming salary, excluded."};}
 if(name==="get_balances"){const b=await getAllBalances();const L={ptsb:"PTSB",boi:"Bank of Ireland",revolut:"Revolut"};return{balances:Object.entries(b).map(([k,v])=>({bank:L[k]||k,balance:+(parseFloat(v)||0).toFixed(2)})),total:+Object.values(b).reduce((a,v)=>a+(parseFloat(v)||0),0).toFixed(2)};}
 if(name==="get_income_and_payday"){const n=new Date();const p=await expectedPayday(n.getFullYear(),n.getMonth());const period=window._currentDDPeriod||{};return{monthlyNetIncome:getMonthlyIncome()||0,nextPaydayDay:p,currentPeriodEnd:period.end||null};}
 if(name==="get_direct_debits"){const dds=window._classifiedDDs||[];const L={ptsb:"PTSB",boi:"BoI",revolut:"Revolut"};return{directDebits:dds.map(d=>({name:d.name,amount:d.amount,dayOfMonth:d.dayOfMonth,bank:d.bank?(L[d.bank]||d.bank):"unassigned",paid:!!d.paid,period:d.isPostPayday?"next (salary-covered)":"this",paused:!!d._paused,frequency:d.frequency===0?"weekly":(d.frequency||1)+"-monthly"}))};}
 if(name==="get_pending_this_period"){const dds=window._classifiedDDs||[];const L={ptsb:"PTSB",boi:"BoI",revolut:"Revolut"};const pre=_prePaydayDDs(dds);const paused=_pausedDDs(dds);const post=_postPaydayDDs(dds);const map=d=>({name:d.name,amount:d.amount,day:d.dayOfMonth,bank:d.bank?(L[d.bank]||d.bank):"unassigned"});const sum=arr=>+arr.reduce((a,d)=>a+d.amount,0).toFixed(2);return{pendingBeforePayday:pre.map(map),pendingBeforePaydayTotal:sum(pre),pausedNotCounted:paused.map(map),pausedTotal:sum(paused),coveredByNextSalary:post.map(map),coveredByNextSalaryTotal:sum(post),note:"pendingBeforePaydayTotal is the only figure that reduces safe-to-spend; quote it verbatim. paused DDs do NOT debit unless resumed (do not subtract them). coveredByNextSalary belongs to the NEXT period after payday; salary covers them, do not subtract."};}
 if(name==="get_debts"){const dt=await dbGetAll("debts");return{debts:dt.map(d=>({name:d.name,type:d.type,balance:d.balance,apr:d.rate,monthlyPayment:d.monthlyPayment||0,limit:d.limit||null,dueDay:d.dueDayOfMonth||null}))};}
 if(name==="get_savable_this_period"){const b=await getAllBalances();const total=Object.values(b).reduce((a,v)=>a+(parseFloat(v)||0),0);const dds=window._classifiedDDs||[];const pre=_prePaydayDDs(dds);const post=_postPaydayDDs(dds);const ddBefore=pre.reduce((a,d)=>a+d.amount,0);const savableBeforeVariable=total-ddBefore;const period=window._currentDDPeriod||{};let days=null;if(period.end){const end=new Date(period.end);const now=new Date();days=Math.max(0,Math.ceil((end-now)/86400000));}const monthlyVar=(getBudgetCats()||[]).reduce((a,x)=>a+(x.amount||0),0);const estVar=days!=null?+((monthlyVar/30)*days).toFixed(2):null;const realistic=estVar!=null?+(savableBeforeVariable-estVar).toFixed(2):null;return{savableBeforeVariable:+savableBeforeVariable.toFixed(2),totalBalance:+total.toFixed(2),ddsBeforePayday:+ddBefore.toFixed(2),daysUntilPayday:days,monthlyVariableBudget:+monthlyVar.toFixed(2),estimatedVariableBeforePayday:estVar,realisticSavableAfterEstimatedVariable:realistic,coveredByNextSalary:post.map(d=>({name:d.name,amount:d.amount,day:d.dayOfMonth})),note:"HEADLINE savableBeforeVariable. Then reality-check: ~estimatedVariableBeforePayday over daysUntilPayday days, realistically ~realisticSavableAfterEstimatedVariable. Post-payday DDs NOT subtracted."};}
 if(name==="get_spending_by_category"){const m=input.months||3;const tx=await dbGetAll("transactions");const co=new Date();co.setMonth(co.getMonth()-m);const cs=co.toISOString().slice(0,10);const bc={};tx.filter(t=>!t.isCredit&&!t.isInternal&&t.date>=cs).forEach(t=>{bc[t.category||"Unknown"]=(bc[t.category||"Unknown"]||0)+t.amount;});return{months:m,byCategory:Object.entries(bc).sort((a,b)=>b[1]-a[1]).map(([ct,t])=>({category:ct,total:+t.toFixed(2),perMonth:+(t/m).toFixed(2)}))};}
 if(name==="search_transactions"){const q=(input.query||"").toLowerCase();const wild=(q===""||q==="*");const tx=await dbGetAll("transactions");let start=null,end=null,winSrc="months";if(input.startDate||input.endDate){start=input.startDate||null;end=input.endDate||null;winSrc="explicit";}else if(input.period){const w=_periodWindow(input.period);if(w){start=w.start;end=w.end;winSrc="period:"+input.period;}}if(!start&&!end){const m=input.months||6;const co=new Date();co.setMonth(co.getMonth()-m);start=co.toISOString().slice(0,10);winSrc="months:"+m;}const bank=(input.bank||"").toLowerCase();const mt=tx.filter(t=>{if(t.isInternal)return false;if(start&&t.date<start)return false;if(end&&t.date>=end)return false;if(bank&&(t.bank||"").toLowerCase()!==bank)return false;if(!wild&&!((t.description||"").toLowerCase().includes(q)||(t.category||"").toLowerCase().includes(q)))return false;return true;});const tot=mt.reduce((a,t)=>a+t.amount,0);return{query:input.query||"(all)",window:winSrc,periodStart:start,periodEnd:end,bankFilter:bank||"all",count:mt.length,totalSpent:+tot.toFixed(2),average:mt.length?+(tot/mt.length).toFixed(2):0,note:"Searched transaction dates from periodStart (inclusive) to periodEnd (exclusive). State this exact window. period/last uses salary dates from settings.",transactions:mt.slice(0,40).map(t=>({date:t.date,description:t.description,amount:t.amount,category:t.category,bank:t.bank||""}))};}
 if(name==="find_recurring_charges"){const tx=await dbGetAll("transactions");const sd=_salaryDates().slice().sort();const today=new Date().toISOString().slice(0,10);let idx=-1;for(let i=0;i<sd.length;i++){if(sd[i]<=today)idx=i;}const winStart=sd[Math.max(0,idx-3)]||null;const winEnd=sd[idx]||today;const inWin=tx.filter(t=>!t.isInternal&&(!winStart||t.date>=winStart)&&t.date<winEnd);const periods=[];for(let p=Math.max(0,idx-3);p<idx;p++){if(sd[p]&&sd[p+1])periods.push([sd[p],sd[p+1]]);}const periodOf=d=>{for(let i=0;i<periods.length;i++){if(d>=periods[i][0]&&d<periods[i][1])return i;}return -1;};const groups={};inWin.forEach(t=>{const k=_normMerchant(t.description);if(!k)return;(groups[k]=groups[k]||[]).push(t);});const dds=window._classifiedDDs||[];const ddKeys=dds.map(d=>_normMerchant(d.name));const recurring=[];Object.entries(groups).forEach(([k,arr])=>{const ps=new Set(arr.map(t=>periodOf(t.date)).filter(i=>i>=0));if(ps.size<2)return;const amts=arr.map(t=>t.amount);const avg=amts.reduce((a,v)=>a+v,0)/amts.length;const within=amts.filter(a=>Math.abs(a-avg)<=avg*0.2).length;if(within<Math.ceil(amts.length*0.6))return;const days=arr.map(t=>parseInt(t.date.slice(8,10),10));const dayAvg=Math.round(days.reduce((a,v)=>a+v,0)/days.length);const inSchedule=ddKeys.some(dk=>dk&&(dk.includes(k)||k.includes(dk)));recurring.push({merchant:arr[arr.length-1].description,normalized:k,avgAmount:+avg.toFixed(2),typicalDay:dayAvg,timesSeen:arr.length,periodsSeen:ps.size,alreadyInDDSchedule:inSchedule,sampleDates:arr.map(t=>t.date).slice(-3)});});recurring.sort((a,b)=>b.avgAmount-a.avgAmount);const notInSchedule=recurring.filter(r=>!r.alreadyInDDSchedule);return{windowStart:winStart,windowEnd:winEnd,periodsAnalysed:periods.length,recurringCount:recurring.length,notInSchedule:notInSchedule,allRecurring:recurring,note:"notInSchedule = recurring charges (seen in >=2 of last 3 pay periods, similar amount) NOT yet tracked as DDs - these are candidates to add. allRecurring includes ones already scheduled. Matching is fuzzy on merchant name."};}
 if(name==="get_goals"){let g=[];try{g=await dbGetAll("goals");}catch(e){}return{goals:g.map(x=>({name:x.name,type:x.type,target:x.targetAmount,targetDate:x.targetDate||null,saved:x.savedSoFar||0,monthlyContribution:x.monthlyContribution||0}))};}
 return{error:"Unknown tool: "+name};}catch(err){return{error:err.message};}}
function buildToolSystemPrompt(){const now=new Date();return "You are VaultLocal AI, a private financial assistant. Data is local. Use euro. Be concise. Today is "+now.toLocaleDateString("en-IE",{weekday:"long",day:"numeric",month:"long",year:"numeric"})+". ALWAYS call the relevant tool before answering. NEVER guess, re-derive, or re-sum numbers in prose: quote each tool's returned figures EXACTLY as given (safeToSpend, pendingBeforePaydayTotal, savableBeforeVariable, etc.). If asked a follow-up, re-read the same tool value rather than recomputing. For 'pending DDs' or 'DDs left this month' use get_pending_this_period and quote pendingBeforePaydayTotal; list paused and salary-covered DDs separately and never add them into the pending total. LOGIC: 1) get_safe_to_spend = balance minus unpaid DDs BEFORE payday; post-payday DDs (coveredByNextSalary) NOT counted, salary covers them, mention only as heads-up. 2) How much can I save -> get_savable_this_period: HEADLINE savableBeforeVariable, THEN reality-check that based on the variable budget youd typically spend about estimatedVariableBeforePayday euro over daysUntilPayday days so realistically about realisticSavableAfterEstimatedVariable euro; never count post-payday DDs against savings. 3) Afford X based on history -> search_transactions, try category terms like eating out or restaurant if exact word finds nothing. 4) Which bank -> get_direct_debits. 5) This period or next -> period field, next means salary-covered. 6) Surplus priority: goals/pre-orders soonest, then planned purchases, then overpay highest-APR loan.";}
async function callBedrockChatWithTools(history){const url=(localStorage.getItem("bedrock_proxy_url")||"").trim();const key=(localStorage.getItem("bedrock_api_key")||"").trim();if(!url)return"Bedrock proxy URL not configured.";let messages=history.map(m=>({role:m.role==="assistant"?"assistant":"user",content:m.content}));const system=buildToolSystemPrompt();for(let turn=0;turn<6;turn++){const res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json",...(key?{"x-api-key":key}:{})},body:JSON.stringify({messages,system,tools:AI_TOOLS,max_tokens:4096})});if(!res.ok){const t=await res.text();return"AI error: "+res.status+" "+t;}const data=await res.json();const content=data.content||[];const toolUses=content.filter(c=>c.type==="tool_use");if(toolUses.length===0){return content.filter(c=>c.type==="text").map(c=>c.text).join("\n")||"(no response)";}messages.push({role:"assistant",content});const toolResults=[];for(const tu of toolUses){console.log("[AI tool]",tu.name,tu.input);const out=await runAITool(tu.name,tu.input);console.log("[AI result]",tu.name,out);toolResults.push({type:"tool_result",tool_use_id:tu.id,content:JSON.stringify(out)});}messages.push({role:"user",content:toolResults});}return"AI stopped after too many tool calls.";}
async function getGoals(){try{return await dbGetAll("goals");}catch(e){return[];}}
async function saveGoal(g){return await dbPut("goals",g);}
console.log("[ai-tools] loaded:",typeof callBedrockChatWithTools);
